### ISSUE TITLE
review process for uploaded data

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/data-preprocessing#11]
As a   user, I want the content outside the model drafts to automatically go through   a review process so that I can be sure that the data I download is correct.

**Comment by christian-rli** [comment]
RequirementSpecificationID=27

**Comment by christian-rli** [comment]
A review process has been set in place for the metadata. There is an [issue template](https://github.com/OpenEnergyPlatform/data-preprocessing/issues/new/choose) for the review of metadata as well as a [manual](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/manual/review_manual.md) on how to review metadata. Suggested improvements to any of these can be filed in the other issue template behind the link above.

Can this issue be closed? If not, please define what else is needed to close this issue.

**Comment by christian-rli** [comment]
reworking the manual. once done this issue can be closed. further improvements to the file will be tackled in new issues.
