### ISSUE TITLE
review/SzenarienDB_conversion_text

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/data-preprocessing#29]
We have uploaded the two  tables related to units/metrics and conversion to model_draft and submit them to the review process

Metadata and file for review: 
1. SzenDB_meta_units
    * ~~https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/SzenarienDB_conversion_text/data-review/SzenDB_meta_units.json~~
    * ~~https://openenergy-platform.org/dataedit/view/model_draft/szenariendb_units~~
1. SzenDB_meta_conversion
    * ~~https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/SzenarienDB_conversion_text/data-review/SzenDB_meta_conversion.json~~
    * ~~https://openenergy-platform.org/dataedit/view/model_draft/szenariendb_conversion~~

Reviewed and published data:
1. szenariendb_units
    * [Metadata](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/reference.szenariendb_units)
    * [Data](https://openenergy-platform.org/dataedit/view/reference/szenariendb_units)
1. szenariendb_conversion
    * [Metadata](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/reference.szenariendb_conversion)
    * [Data](https://openenergy-platform.org/dataedit/view/reference/szenariendb_conversion)

**Comment by christian-rli** [comment]
I made a few small changes to the strings. Everything seems plausible. Do you have a preferred schema where the tables should be moved to?

**Comment by han-f** [comment]
Thanks @christian-rli . @l-emele  had a few further suggestions on how to improve the tables themselves. This may result in changes of the metadata, too. How do you think we should best proceed with this? Keep tables in model_draft, overwrite them there and resubmit metadata (if it did change)? If yes, then we could keep this ticket open until we know whether the metadata has changed and react accordingly once we know?

**Comment by christian-rli** [comment]
I'd suggest just keeping this issue open @han-f . You can change the tables in model_draft and let me know here when you're done. Then there is no need to resubmit the metadata :) 

If there are any relevant changes, you/I can make the necessary updates to the metadata (just commit your changes and reference this issue) and I can upload them afterwards.

**Comment by wingechr** [comment]
files have been updated. please review.

**Comment by l-emele** [comment]
For clarification: We not only update the metadata but also the table structure and the data on the OEP.

**Comment by l-emele** [comment]
Unfortunately this review is now pending for almost three months. Could someone please review?

**Comment by Ludee** [comment]
Review of metadata and move of data finished!
