### ISSUE TITLE
FFE - OSM NUTS-3 regions 2013 (generalized)

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/data-preprocessing#3]
Contributed data set: derived OSM NUTS-3 regions.

* 2018-04-25 Received review request via mail
* 2018-04-26 Received data via OEP-API
* 2018-04-27 Received metadata string via mail
* 2018-04-30 Add metadata string and data to review process
* 2018-05-08 Data published with version 'v1' at [boundaries.ffe_osm_nut3](http://oep.iks.cs.ovgu.de/dataedit/view/boundaries/ffe_osm_nut3)

Link to metadata: https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/boundaries.ffe_osm_nuts3.sql

EDIT: This is the "first official data review" in the OEP. See #2 for general information.

**Comment by Ludee** [comment]
Metadata string passed the review with minor changes in style and content.
Data review will follow as soon as access rights are granted.
@MGlauer please grant owner on _sandbox.osm_nuts3_ to _oeuser_.

**Comment by Ludee** [comment]
Inconsistent use of English:
_{"name": "geom", "description": "Generalisierte Geometrie", "unit": "none"}_

Added _"deu"_ to languages. Other option is to translate column description.

**Comment by Ludee** [comment]
* 2018-05-08 Access rights have been granted

data types:
**id** serial
**version** text
**nuts_code** varchar(5)
**geom** geometry(MultiPolygon,3035)

**Comment by Ludee** [comment]
It is missing which version of the sources (OSM and BKG) were used.

**Comment by Ludee** [comment]
Geometry check passed! No invalid geometries.

**Comment by Ludee** [comment]
Data set available here:
http://www.openenergyplatform.org/dataedit/view/boundaries/ffe_osm_nut3

**Comment by christian-rli** [comment]
Whille a comprehensive description of the review process is still missing , this "first official data review" appears to be completed. Can this issue be closed? Issue #2 may still reference it when closed.

**Comment by christian-rli** [comment]
The [comprehensive description of the review process](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/manual/review_manual.md) is now available. No further tasks seem to be open. Therefore closing this issue.
