### ISSUE TITLE
model_draft instead of sandbox?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/data-preprocessing#32]
Shouldnt it read 

Write data to the database schema _model_draft_ using the OEP-API (template here) 
Instead of 
Write data to the database schema _sandbox_ using the OEP-API (template here)?

Here: https://github.com/OpenEnergyPlatform/data-preprocessing/wiki

**Comment by christian-rli** [comment]
You're right @han-f . I fixed it.
