### ISSUE TITLE
review/SzenarienDB_GWP

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/data-preprocessing#40]
I have just uploaded Global Warming Potential values to this table:
* https://openenergy-platform.org/dataedit/view/model_draft/szenariendb_gwp

Target schema is: **climate.szenariendb_gwp**.

The metadata is in the file https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/SzenarienDB_GWP/data-review/climate.szenariendb_gwp.json on the branch **review/SzenarienDB_GWP**.

## Metadata and data for review

climate.szenariendb_gwp
**Metadata:** ~~https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/SzenarienDB_conversion_text/data-review/SzenDB_meta_units.json~~
**Data:** ~~https://openenergy-platform.org/dataedit/view/model_draft/szenariendb_units~~

## Reviewed and published metadata and data

**schema.tablename**
* [Metadata]()
* [Data]()

**Comment by stap-m** [comment]
I made some minor changes in the metadata string. Everything looks fine to me now. Since this is my first review here, can @christian-rli or @Ludee please also take a look?

**Comment by christian-rli** [comment]
I had a look and made a few additions, mainly a couple typos and supplying the keys whose values contain null. Looks good to me now. Could you have another look as well @jh-RLI (many eyes principle)? I'm not sure I added all the keys. 

Also it appears that foreignKeys is not implemented in our template/example files @Ludee . I was unsure how to deal with empty lists and whether to put a null value there, or to just leave the list empty.

**Comment by jh-RLI** [comment]
Added the path to this review. Looks fine to me now.

**Comment by l-emele** [comment]
> I would suggest creating a pull request that closes this issue after all open tasks are done.

@jh-RLI: What exactly are the open tasks? Which metadata parts should we change in the file https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/SzenarienDB_GWP/data-review/climate.szenariendb_gwp.json?

**Comment by jh-RLI** [comment]
@l-emele according to my understanding, the review of the metadata is complete.  The next step is to append the metadata string to the table. Also make sure that the string is displayed correctly on the openenergy-platform.org. 
@christian-rli I'm not sure what the current workflow is like with the OEP-API (add metadata to table). 

In the last step, the table should be moved from model_draft to the target scheme (climate). Then the pull-request can be merged and the issue can be closed.

If it is unclear how these steps should be implemented it would be sufficient to create the pull-request to specify the open tasks and link a developer (@jh-RLI, @christian-rli, ...)

**Comment by l-emele** [comment]
As we got the okay from the lawyer we uploaded now the full GWP table. Additionally we took advice from a colleague and added a couple of columns with further information. This lead to an update of the metadata. I have upload the new metadata to both the OEP and to https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/SzenarienDB_GWP/data-review/climate.szenariendb_gwp.json

@Ludee @christian-rli @stap-m : Could some one please do a second review of the metadata?
