### ISSUE TITLE
review/my_example_table_rschmitz

### ISSUE THREAD

**Issue by Richard-Schmitz** [OpenEnergyPlatform/data-preprocessing#41]
I have uploaded my first example table following the Guidance "Upload data to the OpenEnergy Platform and initiate review process" and would like to submit it to the review process:

https://openenergy-platform.org/dataedit/view/model_draft/my_example_table_rschmitz

I added the meta data json file in the following pull request:

https://github.com/Richard-Schmitz/data-preprocessing/pull/1

Edits:
1) I had to use the fork "Richard-Schmitz/data-preprocessing" since I was not able to upload directly to "OpenEnergyPlatform/data-preprocessing/data-review"
2) I can neither assign Ludee nor choose "review" as a label as it is both recommended in the Guidance

**Comment by Ludee** [comment]
I added you to the organisation

**Comment by Richard-Schmitz** [comment]
Thank you, I thought that I was already a member.

I added the meta data json file in another following pull request without the fork:

https://github.com/OpenEnergyPlatform/data-preprocessing/pull/42

**Comment by steull** [comment]
After discussion with @Ludee, this issue will now be closed. It is only a sample metadata string that does not contain any data.
