### ISSUE TITLE
review/metadata_HeatDemandProfiles

### ISSUE THREAD

**Issue by MaGering** [OpenEnergyPlatform/data-preprocessing#43]
I've uploaded two metadata files on the branch review/metadata_HeatDemandProfiles. They are ready to be reviewed.

- oemof_heat_HeatDemandProfiles.json:
https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/metadata_HeatDemandProfiles/data-review/oemof_heat_HeatDemandProfiles.json

- oemof_heat_Tables_in_Annex60_2_2_ReferenceCaseStudy-v1.0.json:
https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/metadata_HeatDemandProfiles/data-review/oemof_heat_Tables_in_Annex60_2_2_ReferenceCaseStudy-v1.0.json

**Comment by christian-rli** [comment]
Nice work! Only a few comments / additions: 
* The values for "path" within resources should direct to the specific csv files they describes - not the pdf file its content is taken from. The pdf file is already referenced in the header. The metadata string describes the data it is placed next to. So once you have a final link to the published csv-files, enter those links as the path values.
* I added KU Leuven (as data creators) and RLI (as metadata creators) in the contributors
* I changed "-" values for units to null

**Comment by christian-rli** [comment]
Suggestion for json-viewer: https://jsonformatter.org/json-viewer

**Comment by MaGering** [comment]
Perfect! Thank you @christian-rli

**Comment by christian-rli** [comment]
Review is complete, therefore closing this issue
