### ISSUE TITLE
Incomplete tutorial oem2orm and wrong repository

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/data-preprocessing#53]
The tutorial in this repository on the branch feature/oep-upload-oem2orm is incomplete. Fix the following:

- [x] Inform users that red output is fine in that one command
- [x] Fix error when first executing oem2orm.create_tables(db, ordered_orm)
- [ ] Include sample gpkg-file to make it completely self reliant
- [x] Make sure it runs all the way through, including the tests that data are on the DB
- [x] Move it to the examples/tutorials repository

**Comment by jh-RLI** [comment]
@christian-rli Since there is already a tutorial for Upload data, this would be redundant. For the user, it is surely useful to go through the whole process. But maybe it is reasonable to refer to the next tutorial.

**Comment by jh-RLI** [comment]
https://github.com/OpenEnergyPlatform/oedialect/issues/34

**Comment by christian-rli** [comment]
> @christian-rli Since there is already a tutorial for Upload data, this would be redundant. For the user, it is surely useful to go through the whole process. But maybe it is reasonable to refer to the next tutorial.

There is no tutorial that leads through the entire process in the recommended manner. It's true that there is another upload tutorial, but oem2orm will need to be merged into that or the other way around. There needs to be one complete best practice upload manual. 

I think starting from the beginning (oem2orm) will be the easiest way to build it. Do feel free to copy parts of the other tutorials, we can clean up redundancies later.

**Comment by christian-rli** [comment]
@jh-RLI you checked a couple of boxes. Did you start working on a new branch for that or did you forget to push your changes?

**Comment by jh-RLI** [comment]
@christian-rli I have linked the branch as PR. Currently this is the branch where I developed the tool and the tutorials. I can move the tutorials to the tutorials repo. soon.

**Comment by christian-rli** [comment]
> @christian-rli I have linked the branch as PR. Currently this is the branch where I developed the tool and the tutorials. I can move the tutorials to the tutorials repo. soon.

ok. thanks for clearing this up

**Comment by jh-RLI** [comment]
The oem2orm tool got its own repository. All development is moved there.
