### ISSUE TITLE
Review of szenariendb_mmr_de

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/data-preprocessing#58]
## Issue description

* Branch: review/szenariendb_mmr_de
* Commit: 46959ffe4c4f185ed98c5f79bdef9ed1fa9fdd83
* File: https://github.com/OpenEnergyPlatform/data-preprocessing/pull/49/commits/46959ffe4c4f185ed98c5f79bdef9ed1fa9fdd83#diff-6406948d2f4927eb983f86b6b22c8d69
* Pull Request: https://github.com/OpenEnergyPlatform/data-preprocessing/pull/49
* Table: https://openenergy-platform.org/dataedit/view/scenario/szenariendb_mmr_de

## Workflow checklist

- [x] I have submitted this issue to have my metadata reviewed
- [x] I have uploaded my data to the OEP
- [x] The string is pushed to a new branch
- [x] There is a pull request to master for this branch
- [x] A reviewer started working on the issue
- [x] A reviewer finished working on this issue (and awarded a badge)
- [x] Data moved to its final schema
- [x] The branch for this issue is merged into master and the issue can be closed

**Comment by christian-rli** [comment]
I made a few changes. It looks like you started with an older version of the metadata string (since the licences under the sources key were missing some subkeys), but it should be good now. The file can be parsed with omi as is. If you don't object to any of the changes @wingechr , I would end the review :)

**Comment by han-f** [comment]
Danke @christian-rli  - looks ok so far, but I see you made changes to the original license. It now reads in the subfields CC BY 4.0, whereas on the eionet website it is published as CC BY 2.5 DK (https://creativecommons.org/licenses/by/2.5/dk/deed.en_GB). 
Was there a reason you changed this?

**Comment by christian-rli** [comment]
Thanks for checking @han-f ! You're right. I just saw the CC logo and thought I knew what was going on. I fixed the spdx identifiers and names and it should be fine now. With no further comments I'd end the review.

**Comment by han-f** [comment]
I have checked the data on how it is displayed on the OEP  now.The original license is not rendered in the metadata display. Under "Sources" field "Licenses" it reads: _There is no valid entry for this field_ 
Is there a way to fix this post the move to target schema?  It should indicate CC BY 2.5 DK. 
https://creativecommons.org/licenses/by/2.5/dk/deed.en_GB

**Comment by wingechr** [comment]
* The metadata from the api (https://openenergy-platform.org/api/v0/schema/scenario/tables/szenariendb_mmr_de/meta/) show an empty array for `sources/0/licenses`

**Comment by han-f** [comment]
How can we add it to the metadata now that it is already in its target schema?

**Comment by han-f** [comment]
How can we add it to the metadata now that it is already in its target schema?

**Comment by han-f** [comment]
I realised we can change metadata in the target schema via the interface. I made the correction and amended the metadata accordingly.
