### ISSUE TITLE
open_eGo - ding0 data

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/data-preprocessing#7]
Contributed data sets: [ding0 result data](https://github.com/openego/ding0/tree/master)

- 2018-06-18 Received review request in personal conversation
- 2018-06-18 Data imported in schema "model_draft", no metadata yet
- 2018-06-18 Open new review branch and add metadata string and data to review process

Material:

- [ding0 pull request](https://github.com/openego/ding0/pull/264)
- [Import script](https://github.com/openego/ding0/blob/features/stats-export/ding0/tools/results.py#L2250-L2565) 
- [ding0 run metadata](https://github.com/openego/ding0/blob/9cc9e2ef5f2dc1ff7053de481cd848487bec8da4/ding0/core/__init__.py#L1764-#L1823)

Data (model_draft):
* model_draft.ego_grid_ding0_hvmv_transformer
* model_draft.ego_grid_ding0_line
* model_draft.ego_grid_ding0_lv_branchtee
* model_draft.ego_grid_ding0_lv_generator
* model_draft.ego_grid_ding0_lv_grid
* model_draft.ego_grid_ding0_lv_load
* model_draft.ego_grid_ding0_lv_station
* model_draft.ego_grid_ding0_mv_branchtee
* model_draft.ego_grid_ding0_mv_circuitbreaker
* model_draft.ego_grid_ding0_mv_generator
* model_draft.ego_grid_ding0_mv_grid
* model_draft.ego_grid_ding0_mv_load
* model_draft.ego_grid_ding0_mv_station
* model_draft.ego_grid_ding0_mvlv_mapping
* model_draft.ego_grid_ding0_mvlv_transformer
* model_draft.ego_grid_ding0_versioning

Data (versioning):

- grid.ego_ding0_hvmv_transformer
- grid.ego_ding0_line
- grid.ego_ding0_lv_branchtee
- grid.ego_ding0_lv_generator
- grid.ego_ding0_lv_grid
- grid.ego_ding0_lv_load
- grid.ego_ding0_lv_station
- grid.ego_ding0_mv_branchtee
- grid.ego_ding0_mv_circuitbreaker
- grid.ego_ding0_mv_generator
- grid.ego_ding0_mv_grid
- grid.ego_ding0_mv_load
- grid.ego_ding0_mv_station
- grid.ego_ding0_mvlv_mapping
- grid.ego_ding0_mvlv_transformer

**Comment by Ludee** [comment]
@boltbeard 
Can you please grant all tables to user "oeuser".
A function is here:
https://github.com/openego/ego.io/blob/dev/egoio/tools/db.py#L8-L27

**Comment by boltbeard** [comment]
@Ludee 
Done, There is an example data in the tables mentioned and the `oeuser` has been granted access to the tables.

**Comment by Ludee** [comment]
next step would be creation of the metadata for all **versioning tables.**
I will update the [**ding0_metadata_template**](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/review/ding0/data-review/ding0_metadata_template.json) and create corresponding files automatically. Then we can review the metadata.

**Comment by Ludee** [comment]
Can you please add the created metadata to the repo and link to this issue @jh-RLI . If the first version is added I can help with the necessary versioning scripts. Is the new data release finished @boltbeard?

**Comment by jh-RLI** [comment]
Skript description: Add a metadatastring.json from lokal folder as comment on table:
Includes example and test.
https://github.com/openego/ding0/blob/features/stats-export/ding0/io/read_metadata_file.py

Using a metadatastring.json like:  
https://github.com/OpenEnergyPlatform/examples/blob/master/metadata/metadata_example.json

**Comment by jh-RLI** [comment]
ding0 metadata strings as .json: 
https://github.com/openego/ding0/tree/feature/%23270-ding0_grid_metadatastring/ego_grid_ding0_metadatastrings

**Comment by boltbeard** [comment]
@jh-RLI Thanks for the examples and the pushes to [ding0 pull request #264](https://github.com/openego/ding0/pull/264), @Ludee I'll merge the features of the metadata and the pull request and have a first data release soon.

**Comment by christian-rli** [comment]
@Ludee or @jh-RLI what is still needed to close this issue?

**Comment by jh-RLI** [comment]
As far as I remember this should be okay and can be merged/closed @christian-rli
