### ISSUE TITLE
review/oemof_abbb

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/data-preprocessing#8]
Metadata review process

**Comment by Ludee** [comment]
I can confirm all metadata strings are successfully applied to the database tables.
The OEP displays them correctly. Thank you @christian-rli and @jh-RLI for the good work.

Can you please list all elements, that are still missing. I think the column descriptions and units are not completed for all tables!?

One suggestion: it would be good to add some comments to this issue to better understand the commits you made. Perhaps we create a template with all aspects of the data review for the next ones.
Please compare with the issues #3 and #7.

**Comment by christian-rli** [comment]
Incomplete information for all tables is fully described in still_missing_metadata. Mainly units in oemof_abbb_simulation_parameter are missing. They aren't available in the source table as well. Also, some license-information is missing in oemof_abbb_demand, since the original data were not licensed.

**Comment by christian-rli** [comment]
The review process consisted mainly of reading through the existing metadata-strings and checking for plausibility. URLs were tested and when broken, an attempt was made to replace them. In case of missing units, original data were reviewed. When encountering an empty table (abbb_regions), the table was recreated from the original source data.

**Comment by christian-rli** [comment]
I'm not sure what a 'template' should look like for a review process. An (incomplete) description of an OEP data review process can be found in the wiki: https://github.com/OpenEnergyPlatform/data-preprocessing/wiki
The description is quite helpful, but could be extended and made more instructive for the reviewer.
A few specific review suggestions for a future review process are in the comments of issue #2.

**Comment by christian-rli** [comment]
> Can you please list all elements, that are still missing. I think the column descriptions and units are not completed for all tables!?

 done in the commit referenced in this issue above.

> One suggestion: it would be good to add some comments to this issue to better understand the commits you made. 

Comments were made above.

> Perhaps we create a template with all aspects of the data review for the next ones.

The template issues were created. Therefore closing this issue.
