### ISSUE TITLE
Review: fh_iee_devkopsys

### ISSUE THREAD

**Issue by Richard-Schmitz** [OpenEnergyPlatform/data-preprocessing#83]
## Issue description

I'm submitting an open dataset with a corresponding OEMetadata string for review.
The dataset shows the results from project "Fh IEE DeVKopSys" ("Investigation of development paths in the transport sector in feedback with other sectors of the energy system") of Fraunhofer IEE. It contains a total of 9 different input tables as well as 12 output tables for each of the 2 scenarios.

## Workflow checklist

1. GitHub
- [x] I have submitted this issue to have metadata and data review documented (Issue #NR)
- [x] Create a new review-branch and push OEMetadata to new branch (review/project_nameofdata#NR). If this step is too difficult, attach a file with the metadata as a comment in this issue and let the reviewer know.

2. OEP
- [x] Upload data to the OEP in schema model_draft (see upload tutorial)
- [x] Link URL of data in this issue (model_draft.project_nameofdata)

3. Start a Review
- [x] Start a pull request (PR) from review-branch to master
- [x] Assign a reviewer and get in contact

4. Reviewer section
- [x] A reviewer starts working on the issue
- [x] Review data license
- [x] A reviewer finished working on this issue (and awarded a badge)
- [x] Update metadata on table
- [x] Data moved to its final schema
- [x] Add OEP tags to table
- [ ] Merge PR and delete review-branch
- [ ] Document final links of metadata and data in issue description
- [ ] Close issue

## Metadata and data for review

Here are the links to my data and metadata. Naming follows the pattern model_draft.project_nameofdata:

**Metadata:** 

~~https://github.com/OpenEnergyPlatform/data-preprocessing/pull/82~~
v1.5.1: https://github.com/OpenEnergyPlatform/data-preprocessing/tree/review/fh_iee_devkopsys/data-review/83-fh_iee_devkopsys

**Data:** 

Input data:

https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_biomassepotential
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_cop_zeitreihen
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_ee_potentiale
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_emissionen
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_fahrzeugpotentiale
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_kuppelleistungen
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_laender
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_rahmendaten
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_input_technologieparameter

Output data:

https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_emissionen
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_endenergie
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_fw_bilanz
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_fw_erzeugung
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_gebaeude
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_h2_erzeugung
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_interkonnektoren
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_speicher
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_strom_bilanz
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_strom_erzeugung
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_systemkosten
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_base_scenario_verkehr
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_emissionen
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_endenergie
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_fw_bilanz
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_fw_erzeugung
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_gebaeude
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_h2_erzeugung
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_interkonnektoren
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_speicher
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_strom_bilanz
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_strom_erzeugung
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_systemkosten
https://openenergy-platform.org/dataedit/view/model_draft/fh_iee_devkopsys_cost_sensitivity_verkehr

## Reviewed and published metadata and data

Final naming and location of the data and metadata after the review are as follows:
**schema.tablename**
* [Metadata]()
* [Data]()

**Comment by jh-RLI** [comment]
@Richard-Schmitz 
I reviewed your metadata provided in the Pull Request. They look quite good :) , I just made a few minor changes (see commits). I noticed that the characters for umlauts (for example) are not parsed. I assume these are not ASCII characters? I haven't changed that yet. 
I also noticed that all column names are capitalized. Here, the OEP requires all words to be lower case. 

The licence is accepted.

The next step is to select a suitable target scheme. Which schema fits the data best?
Full list of schemata:
https://openenergy-platform.org/dataedit/schemas

**Comment by steull** [comment]
I have updated all metadata from version 1.4 to version 1.5.1. In addition to what Jonas mentioned regarding umlauts and capitalized names, I changed the source to "null" since "own project" is not a valid source. I also made minor adjustments like spatial resolution and timeseries resolution.

**Comment by Ludee** [comment]
I just moved all tables to the `scenario` schema.
The final tables are missing the metadata, I'm not sure if they got lost during the move.

**Comment by Richard-Schmitz** [comment]
I just re-uploaded the metadata here: https://github.com/OpenEnergyPlatform/data-preprocessing/tree/review/fh_iee_devkopsys/data-review/Fh_IEE_DeVKopSys

It seems that they were already included in those two "input" and "output" folders.

**Comment by steull** [comment]
> I just moved all tables to the `scenario` schema. The final tables are missing the metadata, I'm not sure if they got lost during the move. https://openenergy-platform.org/dataedit/view/scenario?query=fh_iee_devkopsys

I added metadata to all tables manually on the OEP.
