### ISSUE TITLE
Review: MODEX consortium - Data harmonisation

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/data-preprocessing#88]
## Issue description

I'm submitting an open dataset with a corresponding OEMetadata string for review. 
Please see **review_process.md** for technical detail.
Describe your dataset shortly here.

## Workflow checklist

1. GitHub
- [x] I have submitted this issue to have metadata and data review documented (Issue #88 )
- [x] Create a new review-branch and push OEMetadata to new branch (review/open_MODEX_consortium). If this step is too difficult, attach a file with the metadata as a comment in this issue and let the reviewer know.

2. OEP
- [x] Upload data to the OEP in schema model_draft (see upload tutorial)
- [x] Link URL of data in this issue (model_draft.project_nameofdata)

3. Start a Review
- [x] Start a pull request (https://github.com/OpenEnergyPlatform/data-preprocessing/pull/87) from review-branch to master
- [x] Assign a reviewer and get in contact

4. Reviewer section
- [x] A reviewer starts working on the issue
- [x] Review data license - no data provided, only the metadata
- [x] A reviewer finished working on this issue (and awarded a badge)
- [x] Update metadata on table
- [x] Data moved to its final schema
- [x] Add OEP tags to table
- [ ] Merge PR and delete review-branch
- [ ] Document final links of metadata and data in issue description
- [ ] Close issue

## Metadata and data for review

Here are the links to my data and metadata. Naming follows the pattern model_draft.project_nameofdata:
**Metadata:** https://github.com/OpenEnergyPlatform/data-preprocessing/tree/review/open_MODEX_consortium/data-review/open_MODEX_consortium
**Data:** not included

## Reviewed and published metadata and data

Final naming and location of the data and metadata after the review are as follows:

* [Metadata: **reference.***](https://openenergy-platform.org/dataedit/view/reference?query=MODEX)
* **Data** not included

**Comment by Ludee** [comment]
Some titles have been updated and tables moved to reference schema.

**Comment by Ludee** [comment]
Tables for open_MODEX as separated by topic are moved now.
