### ISSUE TITLE
Review: MODEX - data publication - I-O Table

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/data-preprocessing#96]
## Issue description

I'm submitting metadata for the MODEX data publication supplementary material I-O-Table.

## Workflow checklist

1. GitHub
- [x] I have submitted this issue to have metadata and data review documented (Issue #NR)
- [x] Create a new review-branch and push OEMetadata to new branch (review/project_nameofdata#NR). If this step is too difficult, attach a file with the metadata as a comment in this issue and let the reviewer know.

2. OEP
- [x] Upload data to the OEP in schema model_draft (see upload tutorial)
- [x] Link URL of data in this issue (model_draft.project_nameofdata)

3. Start a Review
- [x] Start a pull request (PR) from review-branch to master
- [x] Assign a reviewer and get in contact

4. Reviewer section
- [x] A reviewer starts working on the issue
- [x] Review data license
- [x] A reviewer finished working on this issue (and awarded a badge)
- [x] Update metadata on table
- [x] Data moved to its final schema
- [x] Add OEP tags to table
- [ ] Merge PR and delete review-branch
- [ ] Document final links of metadata and data in issue description
- [ ] Close issue

## Metadata and data for review

Here are the links to my data and metadata. Naming follows the pattern model_draft.project_nameofdata:
**Metadata:** https://github.com/OpenEnergyPlatform/data-preprocessing/blob/feature/modex-data-publication/data-review/open_MODEX_consortium/modex_i_o_data_harmonisation.json
**Data:** https://openenergy-platform.org/dataedit/view/model_draft/modex_data_publication_i_o_table

## Reviewed and published metadata and data

Final naming and location of the data and metadata after the review are as follows:
**schema.tablename**
* [Metadata]()
* [Data]()

**Comment by chrwm** [comment]
It would be nice if the review could be processed soon, as the publication citing the table is already accepted.

**Comment by steull** [comment]
@chrwm, I will start with the review this week.
