### ISSUE TITLE
Review: Update metadata to oem151 for KS80 tables

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/data-preprocessing#98]
## Issue description

The metadata has to be updated to oem151 and ontologically annotated. Then it needs to be registered on the databus.

Continues issue #27

Updates metadata of KS80 tables regarding:
- update to OEM v1.5
- annotate isAbout and valueReference for LOD-GEOSS demonstrator use-case

## Workflow checklist

1. GitHub
- [x] I have submitted this issue to have metadata and data review documented (Issue #NR)
- [x] Create a new review-branch and push OEMetadata to new branch (review/project_nameofdata#NR). If this step is too difficult, attach a file with the metadata as a comment in this issue and let the reviewer know.

2. OEP
- [x] Upload data to the OEP in schema model_draft (see upload tutorial)
- [x] Link URL of data in this issue (model_draft.project_nameofdata)

3. Start a Review
- [x] Start a pull request (PR) from review-branch to master
- [x] Assign a reviewer and get in contact

4. Reviewer section
- [x] A reviewer starts working on the issue
- [ ] Review data license
- [ ] A reviewer finished working on this issue (and awarded a badge)
- [ ] Update metadata on table
- [ ] Data moved to its final schema
- [ ] Add OEP tags to table
- [ ] Merge PR and delete review-branch
- [ ] Document final links of metadata and data in issue description
- [ ] Close issue

## Metadata and data for review

Here are the links to my data and metadata. Naming follows the pattern model_draft.project_nameofdata:
**Metadata:** https://github.com/OpenEnergyPlatform/data-preprocessing/tree/review/ksz2050_r2_ks80_to_oem151/data-review/ksz2050_r2/ks80/oem151

**Data:** https://openenergy-platform.org/dataedit/view/scenario?query=&tags=233

or as single tables:

https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_co2_emissions_industrial_processes
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_electricity_consumption
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_electricity_overview
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_energy_and_climate_targets
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_fugitive_emissions
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_ghg_emissions_detailed_data
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_ghg_emissions_from_combustion_by_fuel
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_ghg_emissions_overview
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_parameters_assumptions
https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_primary_and_final_energy_consumption

## Reviewed and published metadata and data

Final naming and location of the data and metadata after the review are as follows:
**schema.tablename**
* [Metadata]()
* [Data]()

**Comment by chrwm** [comment]
log: 50min [d272224](https://github.com/OpenEnergyPlatform/data-preprocessing/commit/d272224cd4b6c35e2b2f0c919cc19b6928ddf613) inserting valueReference-values only

**Comment by steull** [comment]
@chrwm in sources is the title "own projection". I have changed this to "todo" as this is not informative. If it's ok with you, I would change this to either "Öko-Institut" or to the project name if you give me that. Otherwise, I'll change it back to "own projection". Let me know what works best for you.

**Comment by han-f** [comment]
Hi - I am not sure what is going on with the metadata and where, but just wanted to flag that we discussed that metadata information entered by the user should only be changed by the user (or a reviewer after OK from the user). Did you maybe want to address @wingechr in your comment above instead of @chrwm ?

**Comment by steull** [comment]
Hi @han-f, you're absolutely right, and that's why I asked and why I would immediately undo the source with "own projection" as well.
Hopefully this has not led to any confusion.

**Comment by han-f** [comment]
@steull - great then it was only a mixup of github handles :-)
And I think your suggestion is fine to change the source to "Öko-Institut". Please note this then also holds valid for analogous data tables for the KS95 and AMS2012 scenarios.

**Comment by chrwm** [comment]
> Hi - I am not sure what is going on with the metadata and where, but just wanted to flag that we discussed that metadata information entered by the user should only be changed by the user (or a reviewer after OK from the user). Did you maybe want to address @wingechr in your comment above instead of @chrwm ?

@han-f, so am I right in assuming @wingechr created the metadata initially? In the contributor section for all KS80 tables it says only 

```
    "contributors": [
        {
            "title": "Öko-Institut",
            "email": "oedb@oeko.de",
            "date": "2019-06-26",
            "object": "metadata",
            "comment": "Initial version"
        },

```

We need an update of the metadata, as we want to use them to demonstrate the benefits of the databus in finding ontologically annotated data. 

From my perspective, after @steull review, the metadata are good to go. 
Concerning your remark above it then should be changed by the user, who entered it.

Please note, that for testing purposes I needed to already update 2 tables, [here](https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_co2_emissions_industrial_processes), [here](https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks80_fugitive_emissions), with the updated metadata.
